### ISSUE TITLE
More verbose logging + add retry if the request returns non-200

### ISSUE THREAD

**Issue by jeremyyeo** [dpguthrie/dbtc#107]
Some customers are running into errors when triggering jobs:

```python
  File "***********lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*****.py", line 63, in <module>
    run(*sys.argv[1:])
  File "********.py", line 17, in run
    job_trigger = dbt_cloud_client.cloud.trigger_job(account_id = dbt_cloud_account_id,
```

I don't see a way to get any verbose logging so it's hard to say what exactly is in the returned response that isn't confirming here.

**Comment by jeremyyeo** [comment]
I think the problem is - when polling for jobs, sometimes the dbt Cloud API _may_ return non-JSON or empty JSON - this causes dbtc to crash because it doesn't handle this case.

https://stackoverflow.com/questions/16573332/jsondecodeerror-expecting-value-line-1-column-1-char-0

**Comment by jeremyyeo** [comment]
I believe the issue is that the request methods aren't resilient to network errors. Have traced this to the fact that the dbt Cloud API's load balancer can return a 502 error so there is no actual json during `response.json()`: https://github.com/dpguthrie/dbtc/blob/main/dbtc/client/admin.py#L100

We'll probably want to have some sort of retry for such errors I think.

**Comment by dpguthrie** [comment]
Thanks for opening, Jeremy.  I think we can add some retry logic to this pretty simply.  I'll take a look shortly

**Comment by jeremyyeo** [comment]
Hey @dpguthrie - do you know where we would add this? Somewhere here?

https://github.com/dpguthrie/dbtc/blob/143777c9e254e13f53c07df4f9d5bfd791832107/dbtc/client/admin.py#L73-L74

```python
        response = self.session.request(method=method, url=full_url, **kwargs)
        if response.status_code != 200:
		...
        return response
```

**Comment by dpguthrie** [comment]
@jeremyyeo shoudlve linked the PR, but it's now here https://github.com/dpguthrie/dbtc/blob/main/dbtc/client/main.py

Let me know if you think that won't work.
